SPLIT_KEYBOARD = yes
OLED_DRIVER_ENABLE = yes
ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes
LTO_ENABLE = yes
MOUSEKEY_ENABLE = yes

EXTRAFLAGS += -flto
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
